// Code generated by protoc-gen-go. DO NOT EDIT.
// source: accounts.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListAccountsRequest struct {
	// Optional. The maximum number of accounts to return in the response
	PageSize uint32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional. A pagination token returned from a previous call to `Get`
	// that indicates from where search should continue
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional. Used to specify a subset of fields that should be
	// returned by a get operation or modified by an update operation.
	FieldMask *field_mask.FieldMask `protobuf:"bytes,3,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	// Optional. Search criteria used to select the accounts to return.
	// If no search criteria is specified then all accounts will be
	// returned
	//
	// TODO update query language
	// Query expressions can be used to restrict results based upon
	// the account properties where the operators `=`, `NOT`, `AND` and `OR`
	// can be used along with the suffix wildcard symbol `*`.
	//
	// The string properties in a query expression should use escaped quotes
	// for values that include whitespace to prevent unexpected behavior.
	//
	// Some example queries are:
	//
	// * Query `display_name=Th*` returns accounts whose display_name
	// starts with "Th"
	// * Query `email=foo@example.com` returns accounts with
	// `email` set to `foo@example.com`
	// * Query `display_name=\\"Test String\\"` returns accounts with
	// display names that include both "Test" and "String"
	Query                string   `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAccountsRequest) Reset()         { *m = ListAccountsRequest{} }
func (m *ListAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*ListAccountsRequest) ProtoMessage()    {}
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{0}
}

func (m *ListAccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsRequest.Unmarshal(m, b)
}
func (m *ListAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsRequest.Marshal(b, m, deterministic)
}
func (m *ListAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsRequest.Merge(m, src)
}
func (m *ListAccountsRequest) XXX_Size() int {
	return xxx_messageInfo_ListAccountsRequest.Size(m)
}
func (m *ListAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsRequest proto.InternalMessageInfo

func (m *ListAccountsRequest) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListAccountsRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

func (m *ListAccountsRequest) GetFieldMask() *field_mask.FieldMask {
	if m != nil {
		return m.FieldMask
	}
	return nil
}

func (m *ListAccountsRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type ListAccountsResponse struct {
	// The field name should match the noun "accounts" in the method name.  There
	// will be a maximum number of items returned based on the page_size field
	// in the request
	Accounts []*Account `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	// Token to retrieve the next page of results, or empty if there are no
	// more results in the list
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAccountsResponse) Reset()         { *m = ListAccountsResponse{} }
func (m *ListAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*ListAccountsResponse) ProtoMessage()    {}
func (*ListAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{1}
}

func (m *ListAccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsResponse.Unmarshal(m, b)
}
func (m *ListAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsResponse.Marshal(b, m, deterministic)
}
func (m *ListAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsResponse.Merge(m, src)
}
func (m *ListAccountsResponse) XXX_Size() int {
	return xxx_messageInfo_ListAccountsResponse.Size(m)
}
func (m *ListAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsResponse proto.InternalMessageInfo

func (m *ListAccountsResponse) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func (m *ListAccountsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type GetAccountRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Optional. Used to specify a subset of fields that should be
	// returned by a get operation or modified by an update operation.
	FieldMask            *field_mask.FieldMask `protobuf:"bytes,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetAccountRequest) Reset()         { *m = GetAccountRequest{} }
func (m *GetAccountRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountRequest) ProtoMessage()    {}
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{2}
}

func (m *GetAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountRequest.Unmarshal(m, b)
}
func (m *GetAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountRequest.Marshal(b, m, deterministic)
}
func (m *GetAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountRequest.Merge(m, src)
}
func (m *GetAccountRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountRequest.Size(m)
}
func (m *GetAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountRequest proto.InternalMessageInfo

func (m *GetAccountRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetAccountRequest) GetFieldMask() *field_mask.FieldMask {
	if m != nil {
		return m.FieldMask
	}
	return nil
}

type CreateAccountRequest struct {
	// The account id to use for this account
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The account resource to create
	Account              *Account `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{3}
}

func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (m *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(m, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateAccountRequest) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type UpdateAccountRequest struct {
	// The account resource which replaces the resource on the server
	Account *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// The update mask applies to the resource. For the `FieldMask` definition,
	// see https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#fieldmask
	UpdateMask           *field_mask.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateAccountRequest) Reset()         { *m = UpdateAccountRequest{} }
func (m *UpdateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAccountRequest) ProtoMessage()    {}
func (*UpdateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{4}
}

func (m *UpdateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccountRequest.Unmarshal(m, b)
}
func (m *UpdateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccountRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccountRequest.Merge(m, src)
}
func (m *UpdateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAccountRequest.Size(m)
}
func (m *UpdateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccountRequest proto.InternalMessageInfo

func (m *UpdateAccountRequest) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *UpdateAccountRequest) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type DeleteAccountRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccountRequest) Reset()         { *m = DeleteAccountRequest{} }
func (m *DeleteAccountRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountRequest) ProtoMessage()    {}
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{5}
}

func (m *DeleteAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountRequest.Unmarshal(m, b)
}
func (m *DeleteAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountRequest.Merge(m, src)
}
func (m *DeleteAccountRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountRequest.Size(m)
}
func (m *DeleteAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountRequest proto.InternalMessageInfo

func (m *DeleteAccountRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Account struct {
	// The unique identifier for the account.
	// Key. Not nullable. Non reassignable. Read-only.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The name displayed in places where spaces are allowed.
	// This is usually the combination of the users's first name, middle initial and last name.
	// POSIX does not allow whitespace in username, so we use `username` there
	// Corresponds to LDAP:
	// - cn
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// The shorthand username, used for login and display in POSIX systems
	// Corresponds to LDAP:
	// - posixaccount MUST uid
	// - (AD) User MAY samaccountname (limited to 20 chars)
	// Not nullable. Reassignable.
	Username string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	// Specifies the password for the account.
	// Corresponds to LDAP:
	// - posixaccount MAY authPassword
	// Write-only.
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	// The numeric user id. Used for exposing the account using ldap to POSIX systems
	// Corresponds to LDAP:
	// - posixaccount MUST uidnumber
	// Not nullable.
	Uid int64 `protobuf:"varint,5,opt,name=uid,proto3" json:"uid,omitempty"`
	// The primary group id. Used for exposing the account using ldap to POSIX systems
	// Corresponds to LDAP:
	// - posixaccount MUST gidnumber
	// Not nullable.
	Gid int64 `protobuf:"varint,6,opt,name=gid,proto3" json:"gid,omitempty"`
	// The SMTP address for the account, for example, "einstein@example.org".
	// Corresponds to LDAP:
	// - inetorgperson MAY mail
	Mail string `protobuf:"bytes,7,opt,name=mail,proto3" json:"mail,omitempty"`
	// A description, useful for resource accounts
	// Corresponds to LDAP:
	// - posixaccount MAY description
	Description string `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	// Corresponds to LDAP:
	// -
	MemberOf             []*Group `protobuf:"bytes,9,rep,name=member_of,json=memberOf,proto3" json:"member_of,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{6}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Account) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Account) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Account) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Account) GetGid() int64 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *Account) GetMail() string {
	if m != nil {
		return m.Mail
	}
	return ""
}

func (m *Account) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Account) GetMemberOf() []*Group {
	if m != nil {
		return m.MemberOf
	}
	return nil
}

type ListGroupsRequest struct {
	// Optional. The maximum number of groups to return in the response
	PageSize uint32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional. A pagination token returned from a previous call to `Get`
	// that indicates from where search should continue
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional. Used to specify a subset of fields that should be
	// returned by a get operation or modified by an update operation.
	FieldMask *field_mask.FieldMask `protobuf:"bytes,3,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	// Optional. Search criteria used to select the groups to return.
	// If no search criteria is specified then all groups will be
	// returned
	//
	// TODO update query language
	// Query expressions can be used to restrict results based upon
	// the account properties where the operators `=`, `NOT`, `AND` and `OR`
	// can be used along with the suffix wildcard symbol `*`.
	//
	// The string properties in a query expression should use escaped quotes
	// for values that include whitespace to prevent unexpected behavior.
	//
	// Some example queries are:
	//
	// * Query `display_name=Th*` returns accounts whose display_name
	// starts with "Th"
	// * Query `display_name=\\"Test String\\"` returns groups with
	// display names that include both "Test" and "String"
	Query                string   `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGroupsRequest) Reset()         { *m = ListGroupsRequest{} }
func (m *ListGroupsRequest) String() string { return proto.CompactTextString(m) }
func (*ListGroupsRequest) ProtoMessage()    {}
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{7}
}

func (m *ListGroupsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroupsRequest.Unmarshal(m, b)
}
func (m *ListGroupsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroupsRequest.Marshal(b, m, deterministic)
}
func (m *ListGroupsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroupsRequest.Merge(m, src)
}
func (m *ListGroupsRequest) XXX_Size() int {
	return xxx_messageInfo_ListGroupsRequest.Size(m)
}
func (m *ListGroupsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroupsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroupsRequest proto.InternalMessageInfo

func (m *ListGroupsRequest) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListGroupsRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

func (m *ListGroupsRequest) GetFieldMask() *field_mask.FieldMask {
	if m != nil {
		return m.FieldMask
	}
	return nil
}

func (m *ListGroupsRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type ListGroupsResponse struct {
	// The field name should match the noun "group" in the method name.  There
	// will be a maximum number of items returned based on the page_size field
	// in the request
	Groups []*Group `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	// Token to retrieve the next page of results, or empty if there are no
	// more results in the list
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGroupsResponse) Reset()         { *m = ListGroupsResponse{} }
func (m *ListGroupsResponse) String() string { return proto.CompactTextString(m) }
func (*ListGroupsResponse) ProtoMessage()    {}
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{8}
}

func (m *ListGroupsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroupsResponse.Unmarshal(m, b)
}
func (m *ListGroupsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroupsResponse.Marshal(b, m, deterministic)
}
func (m *ListGroupsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroupsResponse.Merge(m, src)
}
func (m *ListGroupsResponse) XXX_Size() int {
	return xxx_messageInfo_ListGroupsResponse.Size(m)
}
func (m *ListGroupsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroupsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroupsResponse proto.InternalMessageInfo

func (m *ListGroupsResponse) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *ListGroupsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type GetGroupRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Optional. Used to specify a subset of fields that should be
	// returned by a get operation or modified by an update operation.
	FieldMask            *field_mask.FieldMask `protobuf:"bytes,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetGroupRequest) Reset()         { *m = GetGroupRequest{} }
func (m *GetGroupRequest) String() string { return proto.CompactTextString(m) }
func (*GetGroupRequest) ProtoMessage()    {}
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{9}
}

func (m *GetGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupRequest.Unmarshal(m, b)
}
func (m *GetGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupRequest.Marshal(b, m, deterministic)
}
func (m *GetGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupRequest.Merge(m, src)
}
func (m *GetGroupRequest) XXX_Size() int {
	return xxx_messageInfo_GetGroupRequest.Size(m)
}
func (m *GetGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupRequest proto.InternalMessageInfo

func (m *GetGroupRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetGroupRequest) GetFieldMask() *field_mask.FieldMask {
	if m != nil {
		return m.FieldMask
	}
	return nil
}

type CreateGroupRequest struct {
	// The group id to use for this group
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The account resource to create
	Group                *Group   `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupRequest) Reset()         { *m = CreateGroupRequest{} }
func (m *CreateGroupRequest) String() string { return proto.CompactTextString(m) }
func (*CreateGroupRequest) ProtoMessage()    {}
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{10}
}

func (m *CreateGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupRequest.Unmarshal(m, b)
}
func (m *CreateGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupRequest.Marshal(b, m, deterministic)
}
func (m *CreateGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupRequest.Merge(m, src)
}
func (m *CreateGroupRequest) XXX_Size() int {
	return xxx_messageInfo_CreateGroupRequest.Size(m)
}
func (m *CreateGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupRequest proto.InternalMessageInfo

func (m *CreateGroupRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateGroupRequest) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type UpdateGroupRequest struct {
	// The group resource which replaces the resource on the server
	Group *Group `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	// The update mask applies to the resource. For the `FieldMask` definition,
	// see https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#fieldmask
	UpdateMask           *field_mask.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateGroupRequest) Reset()         { *m = UpdateGroupRequest{} }
func (m *UpdateGroupRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateGroupRequest) ProtoMessage()    {}
func (*UpdateGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{11}
}

func (m *UpdateGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGroupRequest.Unmarshal(m, b)
}
func (m *UpdateGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGroupRequest.Marshal(b, m, deterministic)
}
func (m *UpdateGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGroupRequest.Merge(m, src)
}
func (m *UpdateGroupRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateGroupRequest.Size(m)
}
func (m *UpdateGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGroupRequest proto.InternalMessageInfo

func (m *UpdateGroupRequest) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *UpdateGroupRequest) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type DeleteGroupRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteGroupRequest) Reset()         { *m = DeleteGroupRequest{} }
func (m *DeleteGroupRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteGroupRequest) ProtoMessage()    {}
func (*DeleteGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{12}
}

func (m *DeleteGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteGroupRequest.Unmarshal(m, b)
}
func (m *DeleteGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteGroupRequest.Marshal(b, m, deterministic)
}
func (m *DeleteGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteGroupRequest.Merge(m, src)
}
func (m *DeleteGroupRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteGroupRequest.Size(m)
}
func (m *DeleteGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteGroupRequest proto.InternalMessageInfo

func (m *DeleteGroupRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type AddMemberRequest struct {
	// The account id to add
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddMemberRequest) Reset()         { *m = AddMemberRequest{} }
func (m *AddMemberRequest) String() string { return proto.CompactTextString(m) }
func (*AddMemberRequest) ProtoMessage()    {}
func (*AddMemberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{13}
}

func (m *AddMemberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMemberRequest.Unmarshal(m, b)
}
func (m *AddMemberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMemberRequest.Marshal(b, m, deterministic)
}
func (m *AddMemberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMemberRequest.Merge(m, src)
}
func (m *AddMemberRequest) XXX_Size() int {
	return xxx_messageInfo_AddMemberRequest.Size(m)
}
func (m *AddMemberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMemberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddMemberRequest proto.InternalMessageInfo

func (m *AddMemberRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RemoveMemberRequest struct {
	// The account id to remove
	// TODO id in the body indt in the url? not necessary ... use empty?
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveMemberRequest) Reset()         { *m = RemoveMemberRequest{} }
func (m *RemoveMemberRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveMemberRequest) ProtoMessage()    {}
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{14}
}

func (m *RemoveMemberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveMemberRequest.Unmarshal(m, b)
}
func (m *RemoveMemberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveMemberRequest.Marshal(b, m, deterministic)
}
func (m *RemoveMemberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveMemberRequest.Merge(m, src)
}
func (m *RemoveMemberRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveMemberRequest.Size(m)
}
func (m *RemoveMemberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveMemberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveMemberRequest proto.InternalMessageInfo

func (m *RemoveMemberRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ListMembersRequest struct {
	PageSize uint32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional. A pagination token returned from a previous call to `Get`
	// that indicates from where search should continue
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional. Used to specify a subset of fields that should be
	// returned by a get operation or modified by an update operation.
	FieldMask *field_mask.FieldMask `protobuf:"bytes,3,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	// Optional. Search criteria used to select the groups to return.
	// If no search criteria is specified then all groups will be
	// returned
	//
	// TODO update query language
	// Query expressions can be used to restrict results based upon
	// the account properties where the operators `=`, `NOT`, `AND` and `OR`
	// can be used along with the suffix wildcard symbol `*`.
	//
	// The string properties in a query expression should use escaped quotes
	// for values that include whitespace to prevent unexpected behavior.
	//
	// Some example queries are:
	//
	// * Query `display_name=Th*` returns accounts whose display_name
	// starts with "Th"
	// * Query `display_name=\\"Test String\\"` returns groups with
	// display names that include both "Test" and "String"
	Query                string   `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListMembersRequest) Reset()         { *m = ListMembersRequest{} }
func (m *ListMembersRequest) String() string { return proto.CompactTextString(m) }
func (*ListMembersRequest) ProtoMessage()    {}
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{15}
}

func (m *ListMembersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMembersRequest.Unmarshal(m, b)
}
func (m *ListMembersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMembersRequest.Marshal(b, m, deterministic)
}
func (m *ListMembersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMembersRequest.Merge(m, src)
}
func (m *ListMembersRequest) XXX_Size() int {
	return xxx_messageInfo_ListMembersRequest.Size(m)
}
func (m *ListMembersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMembersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListMembersRequest proto.InternalMessageInfo

func (m *ListMembersRequest) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListMembersRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

func (m *ListMembersRequest) GetFieldMask() *field_mask.FieldMask {
	if m != nil {
		return m.FieldMask
	}
	return nil
}

func (m *ListMembersRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type ListMembersResponse struct {
	// The field name should match the noun "members" in the method name.  There
	// will be a maximum number of items returned based on the page_size field
	// in the request
	Members []*Account `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	// Token to retrieve the next page of results, or empty if there are no
	// more results in the list
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListMembersResponse) Reset()         { *m = ListMembersResponse{} }
func (m *ListMembersResponse) String() string { return proto.CompactTextString(m) }
func (*ListMembersResponse) ProtoMessage()    {}
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{16}
}

func (m *ListMembersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMembersResponse.Unmarshal(m, b)
}
func (m *ListMembersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMembersResponse.Marshal(b, m, deterministic)
}
func (m *ListMembersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMembersResponse.Merge(m, src)
}
func (m *ListMembersResponse) XXX_Size() int {
	return xxx_messageInfo_ListMembersResponse.Size(m)
}
func (m *ListMembersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMembersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListMembersResponse proto.InternalMessageInfo

func (m *ListMembersResponse) GetMembers() []*Account {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *ListMembersResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type Group struct {
	// The unique identifier for the account.
	// Key. Not nullable. Non reassignable. Read-only.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The name displayed in places where spaces are allowed.
	// POSIX does not allow whitespace in goup names, so we use `groupname` there
	// Corresponds to LDAP:
	// - ponixaccount MUST cn
	// - displayname
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// The shorthand groupname, used for display in POSIX systems
	// Corresponds to LDAP:
	// - groupofnames MUST cn
	// - (AD) Group MAY samaccountname (limited to 20 chars)
	// Not nullable. Reassignable.
	Groupname string `protobuf:"bytes,3,opt,name=groupname,proto3" json:"groupname,omitempty"`
	// The numeric group id. Used for exposing the group using ldap to POSIX systems
	// Corresponds to LDAP:
	// - posixgroup MUST gidnumber
	// Not nullable.
	Gid int64 `protobuf:"varint,4,opt,name=gid,proto3" json:"gid,omitempty"`
	// A description, useful for resource groups
	// Corresponds to LDAP:
	// - posixgroup MAY description
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// groupofnames MUST/MAY member
	Members              []*Account `protobuf:"bytes,6,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{17}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Group) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Group) GetGroupname() string {
	if m != nil {
		return m.Groupname
	}
	return ""
}

func (m *Group) GetGid() int64 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *Group) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Group) GetMembers() []*Account {
	if m != nil {
		return m.Members
	}
	return nil
}

func init() {
	proto.RegisterType((*ListAccountsRequest)(nil), "settings.ListAccountsRequest")
	proto.RegisterType((*ListAccountsResponse)(nil), "settings.ListAccountsResponse")
	proto.RegisterType((*GetAccountRequest)(nil), "settings.GetAccountRequest")
	proto.RegisterType((*CreateAccountRequest)(nil), "settings.CreateAccountRequest")
	proto.RegisterType((*UpdateAccountRequest)(nil), "settings.UpdateAccountRequest")
	proto.RegisterType((*DeleteAccountRequest)(nil), "settings.DeleteAccountRequest")
	proto.RegisterType((*Account)(nil), "settings.Account")
	proto.RegisterType((*ListGroupsRequest)(nil), "settings.ListGroupsRequest")
	proto.RegisterType((*ListGroupsResponse)(nil), "settings.ListGroupsResponse")
	proto.RegisterType((*GetGroupRequest)(nil), "settings.GetGroupRequest")
	proto.RegisterType((*CreateGroupRequest)(nil), "settings.CreateGroupRequest")
	proto.RegisterType((*UpdateGroupRequest)(nil), "settings.UpdateGroupRequest")
	proto.RegisterType((*DeleteGroupRequest)(nil), "settings.DeleteGroupRequest")
	proto.RegisterType((*AddMemberRequest)(nil), "settings.AddMemberRequest")
	proto.RegisterType((*RemoveMemberRequest)(nil), "settings.RemoveMemberRequest")
	proto.RegisterType((*ListMembersRequest)(nil), "settings.ListMembersRequest")
	proto.RegisterType((*ListMembersResponse)(nil), "settings.ListMembersResponse")
	proto.RegisterType((*Group)(nil), "settings.Group")
}

func init() { proto.RegisterFile("accounts.proto", fileDescriptor_e1e7723af4c007b7) }

var fileDescriptor_e1e7723af4c007b7 = []byte{
	// 1068 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x57, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0x96, 0x9b, 0x26, 0x4d, 0x4e, 0x92, 0x76, 0x3b, 0x0d, 0xbb, 0xae, 0x9b, 0x96, 0x30, 0xec,
	0x96, 0x90, 0x2e, 0x49, 0x15, 0x24, 0x24, 0xba, 0xe2, 0xa2, 0xcb, 0x4f, 0x2f, 0x60, 0x01, 0xb9,
	0x8b, 0x90, 0x60, 0xb5, 0x91, 0x1b, 0x4f, 0xc2, 0xd0, 0xc4, 0xf6, 0xda, 0x4e, 0xd8, 0x2e, 0x5a,
	0x09, 0xf1, 0x02, 0x5c, 0xf0, 0x20, 0xfc, 0xdc, 0xf1, 0x1c, 0xbc, 0x00, 0x17, 0x3c, 0x06, 0x17,
	0xc8, 0x33, 0x63, 0x7b, 0xfc, 0x93, 0xa4, 0x80, 0xb8, 0xd8, 0xab, 0xd8, 0xe7, 0x9c, 0x39, 0xdf,
	0x39, 0x73, 0x7e, 0x3e, 0x07, 0x36, 0x8d, 0xe1, 0xd0, 0x9e, 0x59, 0xbe, 0xd7, 0x75, 0x5c, 0xdb,
	0xb7, 0x51, 0xd9, 0x23, 0xbe, 0x4f, 0xad, 0xb1, 0xa7, 0xbd, 0x3c, 0xb6, 0xed, 0xf1, 0x84, 0xf4,
	0x0c, 0x87, 0xf6, 0x46, 0x94, 0x4c, 0xcc, 0xc1, 0x05, 0xf9, 0xca, 0x98, 0x53, 0xdb, 0xe5, 0xa6,
	0x5a, 0x53, 0x32, 0x30, 0x2c, 0xcb, 0xf6, 0x0d, 0x9f, 0xda, 0x96, 0x70, 0xa4, 0xed, 0x09, 0x2d,
	0x7b, 0xbb, 0x98, 0x8d, 0x7a, 0x64, 0xea, 0xf8, 0x57, 0x42, 0xd9, 0x4a, 0x2b, 0x39, 0xc0, 0xd4,
	0xf0, 0x2e, 0xb9, 0x05, 0xfe, 0x45, 0x81, 0x9d, 0x8f, 0xa8, 0xe7, 0x9f, 0x8a, 0xf0, 0x74, 0xf2,
	0x64, 0x46, 0x3c, 0x1f, 0xb5, 0xa0, 0xe2, 0x18, 0x63, 0x32, 0xf0, 0xe8, 0x33, 0xa2, 0x2a, 0x2d,
	0xa5, 0x5d, 0xbf, 0x5f, 0xf8, 0xe3, 0x54, 0xd1, 0xcb, 0x81, 0xf4, 0x9c, 0x3e, 0x23, 0x08, 0x03,
	0x30, 0x0b, 0xdf, 0xbe, 0x24, 0x96, 0xba, 0xd6, 0x52, 0xda, 0x15, 0x6e, 0xc2, 0x0e, 0x3e, 0x0c,
	0xa4, 0xe8, 0x6d, 0x80, 0x18, 0x51, 0x2d, 0xb4, 0x94, 0x76, 0xb5, 0xaf, 0x75, 0x79, 0x50, 0xdd,
	0x30, 0xa8, 0xee, 0x07, 0x81, 0xc9, 0x03, 0xc3, 0xbb, 0xd4, 0x2b, 0xa3, 0xf0, 0x11, 0xed, 0x42,
	0xf1, 0xc9, 0x8c, 0xb8, 0x57, 0xea, 0x7a, 0xec, 0x99, 0x4b, 0xf0, 0x14, 0x1a, 0xc9, 0x90, 0x3d,
	0xc7, 0xb6, 0x3c, 0x82, 0xde, 0x80, 0x72, 0x78, 0xcb, 0xaa, 0xd2, 0x2a, 0xb4, 0xab, 0xfd, 0xed,
	0x6e, 0x78, 0xcd, 0x5d, 0x61, 0xad, 0x47, 0x26, 0xe8, 0x10, 0xb6, 0x2c, 0xf2, 0xd4, 0x1f, 0xa4,
	0xb3, 0xd0, 0xeb, 0x81, 0xf8, 0xd3, 0x30, 0x09, 0xfc, 0x18, 0xb6, 0xcf, 0x48, 0x88, 0x16, 0xde,
	0xcf, 0x26, 0xac, 0x51, 0x93, 0x5d, 0x4c, 0x45, 0x5f, 0xa3, 0x66, 0x2a, 0xd3, 0xb5, 0x7f, 0x90,
	0x29, 0x3e, 0x87, 0xc6, 0xbb, 0x2e, 0x31, 0x7c, 0xb2, 0x02, 0xe2, 0x08, 0x36, 0x44, 0xec, 0xc2,
	0x7f, 0x4e, 0x76, 0xa1, 0x05, 0xfe, 0x4e, 0x81, 0xc6, 0x67, 0x8e, 0x99, 0xf5, 0x2a, 0x79, 0x51,
	0x56, 0x79, 0x41, 0xf7, 0xa0, 0x3a, 0x63, 0x4e, 0xae, 0x9b, 0x16, 0x70, 0x73, 0x96, 0xd7, 0x21,
	0x34, 0xde, 0x23, 0x13, 0xb2, 0x2a, 0x2f, 0xfc, 0x97, 0x02, 0x1b, 0xc2, 0x24, 0x93, 0xf3, 0x2b,
	0x50, 0x33, 0xa9, 0xe7, 0x4c, 0x8c, 0xab, 0x81, 0x65, 0x4c, 0x89, 0x28, 0x50, 0x55, 0xc8, 0x3e,
	0x36, 0xa6, 0x04, 0x69, 0x50, 0x9e, 0x79, 0xc4, 0x65, 0xea, 0x02, 0x53, 0x47, 0xef, 0x81, 0xce,
	0x31, 0x3c, 0xef, 0x1b, 0xdb, 0x35, 0x79, 0x1f, 0xe9, 0xd1, 0x3b, 0xba, 0x01, 0x85, 0x19, 0x35,
	0xd5, 0x62, 0x4b, 0x69, 0x17, 0xf4, 0xe0, 0x31, 0x90, 0x8c, 0xa9, 0xa9, 0x96, 0xb8, 0x64, 0x4c,
	0x4d, 0x84, 0x60, 0x7d, 0x6a, 0xd0, 0x89, 0xba, 0xc1, 0xce, 0xb2, 0x67, 0xd4, 0x82, 0xaa, 0x49,
	0xbc, 0xa1, 0x4b, 0x9d, 0x60, 0x0c, 0xd5, 0xb2, 0x88, 0x28, 0x16, 0xa1, 0xbb, 0x50, 0x99, 0x92,
	0xe9, 0x05, 0x71, 0x07, 0xf6, 0x48, 0xad, 0xb0, 0x46, 0xdc, 0x8a, 0x2f, 0xf9, 0xcc, 0xb5, 0x67,
	0x8e, 0x5e, 0xe6, 0x16, 0x9f, 0x8c, 0xf0, 0x4f, 0x0a, 0x6c, 0x07, 0xed, 0xcc, 0xe4, 0x2f, 0xc4,
	0xfc, 0x11, 0x40, 0x72, 0xc0, 0x62, 0xfa, 0x5e, 0x83, 0xd2, 0x98, 0x49, 0xc4, 0xec, 0x65, 0x52,
	0x16, 0xea, 0x6b, 0xcf, 0xdd, 0x23, 0xd8, 0x3a, 0x23, 0x1c, 0xe5, 0x7f, 0x98, 0xba, 0x0f, 0x01,
	0xf1, 0xa9, 0x5b, 0x0a, 0x70, 0x07, 0x8a, 0x2c, 0x6a, 0xe1, 0x3b, 0x93, 0x13, 0xd7, 0xe2, 0xa7,
	0x80, 0xf8, 0xb0, 0x25, 0x9c, 0x45, 0x87, 0x95, 0x65, 0x87, 0xff, 0xdb, 0x90, 0xdd, 0x06, 0xc4,
	0x87, 0x6c, 0x59, 0x1a, 0x18, 0xc3, 0x8d, 0x53, 0xd3, 0x7c, 0xc0, 0x5a, 0x6e, 0x91, 0xcd, 0x1d,
	0xd8, 0xd1, 0xc9, 0xd4, 0x9e, 0x93, 0xe5, 0x66, 0x3f, 0x2b, 0xbc, 0xfa, 0xdc, 0xea, 0x85, 0xe8,
	0xd7, 0xaf, 0x39, 0xc5, 0x45, 0x11, 0x8b, 0x86, 0x3d, 0x82, 0x0d, 0x3e, 0x84, 0x4b, 0xd8, 0x22,
	0xb4, 0xb8, 0x76, 0xd3, 0xfe, 0xa6, 0x40, 0x91, 0x95, 0xe2, 0xdf, 0xac, 0xb2, 0x26, 0x54, 0x58,
	0x4b, 0x48, 0xbb, 0x2c, 0x16, 0x84, 0xeb, 0x69, 0x3d, 0x5e, 0x4f, 0xa9, 0x55, 0x54, 0xcc, 0xae,
	0x22, 0x29, 0xc7, 0xd2, 0xaa, 0x1c, 0xfb, 0x3f, 0xac, 0xc3, 0x56, 0x48, 0xaa, 0xe7, 0xc4, 0x9d,
	0xd3, 0x21, 0x41, 0x43, 0xa8, 0xc9, 0x5c, 0x8b, 0xf6, 0xe3, 0xf3, 0x39, 0x9f, 0x0d, 0xda, 0xc1,
	0x22, 0x35, 0xbf, 0x73, 0xdc, 0xf8, 0xfe, 0xf7, 0x3f, 0x7f, 0x5c, 0xdb, 0x44, 0xb5, 0xde, 0xfc,
	0xb8, 0x17, 0x31, 0xf1, 0x23, 0x80, 0x98, 0x61, 0xd1, 0x9e, 0x34, 0x27, 0x69, 0xde, 0xd5, 0xb2,
	0xf1, 0xe3, 0x03, 0xe6, 0x53, 0x45, 0x3b, 0xb2, 0xcf, 0xde, 0xb7, 0xd4, 0x7c, 0xa7, 0xf3, 0xfc,
	0x44, 0xe9, 0x20, 0x03, 0xea, 0x09, 0x7e, 0x45, 0x52, 0x90, 0x79, 0xc4, 0x9b, 0x87, 0xb1, 0xcf,
	0x30, 0x6e, 0xe1, 0x44, 0xdc, 0x27, 0x11, 0x4f, 0x3a, 0x50, 0x4f, 0x90, 0xad, 0x0c, 0x91, 0xc7,
	0xc2, 0x79, 0x10, 0x77, 0x19, 0xc4, 0x61, 0x7f, 0x2f, 0x99, 0x86, 0x78, 0xea, 0xf2, 0x74, 0x22,
	0x44, 0x13, 0xea, 0x09, 0x72, 0x95, 0x11, 0xf3, 0x58, 0x57, 0xbb, 0x99, 0x19, 0xa3, 0xf7, 0x83,
	0x0f, 0x45, 0xbc, 0xc7, 0x60, 0x5f, 0xea, 0xe4, 0xdd, 0x5e, 0xff, 0xd7, 0x12, 0xd4, 0xf9, 0x9a,
	0x0f, 0xfb, 0xe1, 0x4b, 0x80, 0x78, 0xf7, 0xcb, 0xa5, 0xca, 0x50, 0x98, 0xd6, 0xcc, 0x57, 0x8a,
	0x4e, 0x40, 0x0c, 0xb7, 0x86, 0x20, 0xc0, 0x15, 0xcc, 0xf0, 0x10, 0xca, 0xe1, 0xc6, 0x47, 0xbb,
	0x89, 0x2e, 0x90, 0xb7, 0x9b, 0x96, 0x5e, 0xa4, 0xb8, 0xc9, 0x7c, 0xdd, 0x44, 0xdb, 0xb1, 0x2f,
	0xa9, 0xfe, 0x9f, 0x43, 0x55, 0xda, 0xf4, 0xa8, 0x99, 0xae, 0xfe, 0x72, 0xdf, 0xbb, 0xcc, 0xf7,
	0x0e, 0x96, 0xe2, 0x3c, 0x11, 0x8b, 0xdb, 0x84, 0xaa, 0xb4, 0xf5, 0x65, 0xc7, 0x59, 0x32, 0xc8,
	0x3a, 0x3e, 0x64, 0x8e, 0x5b, 0xfd, 0x5b, 0x72, 0xd0, 0xec, 0x57, 0xd4, 0x5a, 0xa0, 0x3c, 0x86,
	0xaa, 0xb4, 0xe1, 0x65, 0x94, 0xec, 0xe2, 0x5f, 0x58, 0x65, 0x91, 0x45, 0x27, 0x7b, 0x43, 0x68,
	0x08, 0x95, 0x88, 0x1b, 0x90, 0x26, 0xf5, 0x65, 0x8a, 0x30, 0xb2, 0x19, 0xbc, 0xce, 0x9c, 0xbe,
	0x8a, 0x0f, 0x32, 0x4e, 0x7b, 0x62, 0xa5, 0xf4, 0x6e, 0xbb, 0x64, 0x14, 0xd4, 0x60, 0x0e, 0x35,
	0x99, 0x5c, 0xe4, 0x35, 0x92, 0x43, 0x3a, 0x59, 0xa8, 0xb7, 0x18, 0xd4, 0x71, 0xe7, 0x68, 0x31,
	0x94, 0x34, 0x29, 0xcf, 0x23, 0x5c, 0x17, 0xaa, 0xd2, 0xea, 0x47, 0xa9, 0x96, 0x4c, 0x72, 0x98,
	0xb6, 0xbf, 0x40, 0x2b, 0x3a, 0x56, 0x14, 0x0c, 0xad, 0x48, 0xf7, 0x7e, 0xe3, 0x0b, 0xe4, 0x5c,
	0x8e, 0xf9, 0x7f, 0xae, 0xde, 0xfc, 0xf8, 0x1e, 0x2f, 0x45, 0x89, 0xfd, 0xbc, 0xf9, 0x77, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x66, 0x42, 0x71, 0x8c, 0x09, 0x0e, 0x00, 0x00,
}
